/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.ArrayList;
import objectos.Motor;

/**
 *
 * @author hp
 */
public class Principal extends javax.swing.JFrame {

    public static ArrayList<Motor> motores = new ArrayList<>();
        
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAltaVehiculo = new javax.swing.JButton();
        jbAltaMotor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbAltaVehiculo.setText("Alta Vehiculo");
        jbAltaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaVehiculoActionPerformed(evt);
            }
        });

        jbAltaMotor.setText("Alta Motor");
        jbAltaMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaMotorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jbAltaVehiculo)
                .addGap(130, 130, 130)
                .addComponent(jbAltaMotor)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAltaVehiculo)
                    .addComponent(jbAltaMotor))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAltaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaVehiculoActionPerformed
   
        ABMVehiculo abmVehiculo = new ABMVehiculo();
        abmVehiculo.setVisible(true);
    }//GEN-LAST:event_jbAltaVehiculoActionPerformed

    private void jbAltaMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaMotorActionPerformed
        // TODO add your handling code here:
        ABMMotor abmMotor = new ABMMotor();
        abmMotor.setVisible(true);
        
    }//GEN-LAST:event_jbAltaMotorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAltaMotor;
    private javax.swing.JButton jbAltaVehiculo;
    // End of variables declaration//GEN-END:variables
}
